// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int randomTests = Integer.parseInt(args[0]);
		int testCounter = 0;
		int positiveCounter = 0;
		int negativeCounter = 0;
		while (testCounter < randomTests)
		{
			if (Math.random() > 0.5)
			{
				positiveCounter++;
			}
			else 
			{
				negativeCounter++;
			}
			testCounter++;
		}
		System.out.println("> 0.5: "+positiveCounter+" times");
		System.out.println("<= 0.5: "+negativeCounter+" times");
		double ratio = (double)(Math.min(negativeCounter, positiveCounter)) / (Math.max(negativeCounter, positiveCounter));
		System.out.println("Ratio: "+ratio);
	}
}
